name: Print Hello World on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  print_hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Check if linked to open issue
        run: |
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          linked_issue=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number" \
            | jq --raw-output '.pull_request.url')

          if [[ -n "$linked_issue" ]]; then
            echo "Hello World"
          else
            echo "No linked issue found"
          fi
